targets:
  $default:
    builders:
      freezed:
        options:
          makeCollectionsUnmodifiable: true
        
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          generic_argument_factories: false
          # include_if_null: true