name: fortune
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.1+1

environment:
  sdk: '>=3.4.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  country_code: ^1.0.0
  cupertino_icons: ^1.0.8
  emoji_flag_converter: ^1.1.0
  file_picker: ^8.0.6
  firebase_analytics: ^11.2.1
  firebase_app_check: ^0.3.0+4
  firebase_core: ^3.3.0
  firebase_vertexai: ^0.2.2+3
  flutter:
    sdk: flutter
  flutter_dropzone: ^4.0.1
  flutter_gen: ^5.6.0
  flutter_image_compress: ^2.3.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  go_router: ^14.2.2
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.2.1
  markdown_widget: ^2.3.2+6
  translator: ^1.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_gen_runner: 5.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_lint: ^2.3.10

flutter_gen:
  output: lib/generated/flutter_gen
  integrations:
    flutter_svg: true

# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  # adaptive_icon_background: "assets/app-icon-background.png"
  # adaptive_icon_foreground: "assets/app-icon-foreground.png"

  
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/tellers/
    - assets/faces/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
